### ISSUE TITLE
[Questions] Why not using telepathy ?

### ISSUE THREAD

**Issue by sbernard31** [dino/dino#101]
Firstly, thx to believe there is still a place for free IM application in linux and gnome world. I tried your application and this is really promising.
I would like to ask you some questions. That's real questions, don't take it as a blame :), I just want to understand.

1) Telepathy is a communication framework with backend for XMPP, I would like to know why you choose to not using it ? 

I think (not sure) that using telepathy automatically add integration with `gnome-online-account` and `gnome-contact` as they have telepathy integration.

2) It seems your are using a lib called xmpp-vala, is it a lib you write from scratch ? Could you explain this choice ? 

Thx again :)

**Comment by jubalh** [comment]
I am not a dino developer, but here is what I know:

The Telepathy XMPP backend (Gabble) is out of date. I talked with some devs several months ago and they think a huge rewrite is possible. There have been long discussions on the Telepathy ML and at times people (developers) even thought Telepathy is dead since Corabolla didnt contribute as much as they used to.

Then some people started to invest more time in Telepathy Qt, but Telepathy Glib still lacks behind afaik.

This is the state of some months ago, I didnt check recently so maybe things have changed in the meantime.

**Comment by tonghuix** [comment]
That's true, Telepathy is out of date and lack of security update years ago. So it is totally useless in this modern life (I mean after Edward Snowden).

For ```gnome-online-account```, it also will be obsoleted soon, someone thought it is useless and someone believe it should be rewrite.

I don't know why they choose xmpp-vala, at least, it works perfectly at this time.

**Comment by fiaxh** [comment]
Telepathy Gabble does not seem to be actively maintained for some years now. With that comes that "recently" published XEPs are [not implemented](https://telepathy.freedesktop.org/components/telepathy-gabble/): For example it does not support carbons or message markers. Also, it does not implement any kind of cryptography. Basically we would have to do a lot of work on Telepathy Gabble (and then get the changes to actually be merged) before being able to use it.

Yes, we wrote xmpp-vala from scratch.

**Comment by Mic92** [comment]
I would they this question was answered.
