### ISSUE TITLE
Failure to synchronize all client OMEMO keys in new converastion

### ISSUE THREAD

**Issue by distefam** [dino/dino#1050]
Recently got a new computer and installed Dino on it. I now have three clients using my xmpp account (Snikket account): Dino + Gajim + Android Snikket (Conversations, basically). I sent an OMEMO encrypted message to a new contact from Dino. This contact replied (from Snikket Android) and I am able to decrypt/read her message via Dino but not my other clients. This original message sent via Dino should have included all of my OMEMO keys for my other clients as well.

**Comment by fiaxh** [comment]
> This original message sent via Dino should have included all of my OMEMO keys for my other clients as well.

You seem to have a misconception about how OMEMO works.
Your friend publishes all of her OMEMO keys on her server, one from each of her devices. You publish all of your OMEMO keys on your server. Publishing keys on the server is done automatically by your clients. Clients then fetch keys from the responsible server. Clients don't send keys to other clients.

> I am able to decrypt/read her message via Dino but not my other clients

That likely means that for some reason her client does not encrypt the message to those clients of you.

I can't tell you what exactly the cause of that issue is, but it's not Dino.
