### ISSUE TITLE
Message Carbons ?

### ISSUE THREAD

**Issue by jmaris** [dino/dino#109]
Hey ! 

Does Dino support message carbons ? It's really practical when you have multiple devices :s

**Comment by fiaxh** [comment]
[Yes](https://github.com/dino/dino/wiki/Supported-XEPs), it does (`urn:xmpp:carbons:2`).

**Comment by mweinelt** [comment]
This is weird, because I do have issues with messages not arriving on some clients, probably related to OMEMO usage between Dino and Conversations.

Is this possibly related to carbons or rather on the OMEMO side?

**Comment by fiaxh** [comment]
@mweinelt There was a breaking change in the way Conversations sends OMEMO messages in 1.18.0 which makes it impossible for client versions below 1.16.0 to decrypt the messages. Dino only supports the new version. Current conversation versions can still read both OMEMO versions, but send the new OMEMO version. Thus, if you write messages with a contact that has a Conversation version < 1.16.0, you can read their messages on your mobile but not on Dino, as it can't decrypt the messages. In that case the problem is not related to carbons, as the messages do in fact arrive.

Could that problem fit your scenario?

**Comment by NicoHood** [comment]
I am also chatting with someone using conversations. And sometimes messages are lost on both sides. This rarely happens and we have no idea why this happens.

**Comment by mweinelt** [comment]
@fiaxh Yeah, that sounds about right. Thanks for clearing that up.
