### ISSUE TITLE
OMEMO Public keys lost if contact is offline

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#112]
If you chat with omemo encryption, your contact goes offline and you restart dino (while the contact is offline) you will no longer be able to send him encrypted offline messages. If you switch to unencrypted you sometimes have no chance to get back to omemo. It seems really random how to enable omemo again.

**Comment by silberzwiebel** [comment]
I have a similar problem: I can't send OMEMO encrypted messages to offline contacts, they just not appear at their clients. They are marked in red with an exclamation mark in dino though.

**Comment by MarcelWaldvogel** [comment]
Some technical detail, which might be helpful (and to which I was inspired by #128):

When first starting Dino, only the `device id` is stored in the pubsub storage. Only on the second start, the `bundle` is published as well. This prevents other clients from working with the keys.

I hope this helps hunting the bug.

**Comment by mar-v-in** [comment]
@MarcelWaldvogel interesting catch. Can you tell me which server you are using?

The current behavior of Dino is:
- First it receives the current device list. A proper server should send it directly when connecting (and it's not empty), but I noticed some servers fail to do so, so Dino directly requests the current device list after connecting.
- After it received the device list, it checks if the device list already contains the own device id. If the device id is in the list it will fetch the bundle and update it if required. If the device is not yet on the device list, we update the device list accordingly. The server is supposed to notify the client after the device list was updated which will cause a recheck as above and will finally result in the bundle being published.

My guess is your server fails to send the notification after device list modification. This might happen due to a recent bug in ejabberd.

However to have a more robust implementation, we should either request the device list after modifying it or publish the bundle even if we are not sure to be on the device list yet.

**Comment by MarcelWaldvogel** [comment]
We noticed the problem (Gajim complaining "no bundle for device <number>") on Prosody but went on to ejabberd (17.07) to look at the pubsub store, as it was easier to get at the internal state. So, apparently, both.

Do you have a good tool to look at the pubsub store in Prosody (or generally)? Then we could also do it there "directly" (not only via Gajim), if that would help.

**Comment by DanScharon** [comment]
I saw the complaint "no bundle for device" coming from the Pidgin OMEMO-plugin _lurch_ but Gajim may also emit a similar warning message.

**Comment by MarcelWaldvogel** [comment]
@DanScharon You are right. I named the wrong client (corrected) and paraphrased the error message from memory.

**Comment by silberzwiebel** [comment]
I'm actually not sure if the bug I'm encountering (see https://github.com/dino/dino/issues/112#issuecomment-318830924 ) is this one but I wanted to note that dino still does not send OMEMO encrypted messages to offline contacts while they are successfully send (in reversed order) when the contact comes back online and dino is still running.

**Comment by silberzwiebel** [comment]
I do think that this issue is solved. At least I'm able to send OMEMO encrypted messages to offline users with the latest version.

**Comment by fiaxh** [comment]
Dino's OMEMO implementation has improved and changed a lot since this issue was opened. Thus, I will close the issue. If anyone still experiences problems, please open a new issue.
