### ISSUE TITLE
Allow self-signed certificates for .onion http file upload up+down urls

### ISSUE THREAD

**Issue by fiaxh** [dino/dino#1149]

**Comment by user82622** [comment]
Are there any updates regarding this issue?

**Comment by matthewrfennell** [comment]
I'm interested in contributing to Dino, and gave this a go locally, with a similar callback as [here](https://github.com/dino/dino/commit/81a550527#diff-a1e86d2426a1de98dbfd8c579a08552c37b459be54b9179ba4d0564bb3826afcR375).

However, when testing against [xmpp.is](https://xmpp.is), I saw we are getting `TlsCertificateFlags.BAD_IDENTITY` instead of `TlsCertificateFlags.UNKNOWN_CA`.

This is because (unlike their regular service) their cert for onion services only covers their main URL `6vo[...].onion` - and not their upload URL `http.6vo[...].onion`.

When I allow `TlsCertificateFlags.BAD_IDENTITY` as well, upload and download works fine. But I presume this defeats the point of having the cert in the first place.

So, I wanted to confirm - do we only want to accept these self-signed certs case of `UNKNOWN_CA`?
