### ISSUE TITLE
Is there "test room" for video call?

### ISSUE THREAD

**Issue by Symbian9** [dino/dino#1197]
I'm installed *Dino* `0.3` and want to test it.

Is there any public "test room" for join and try video calls?

**Comment by sonicnkt** [comment]
I think the option to initiate a group call is for private rooms only.
You can also invite more people to an already existing call as well but there is no test room.
Have not tried it yet tho as i am the only dino users with 0.3 available. Most of my friends use the unofficial windows port

**Comment by jscott0** [comment]
For audio calls, one can call `thetestcall\40sip.linphone.org@sip.cheogram.com` (yes, you're reading that right) to see that things are working. Granted if you're not using an XMPP client with a dial pad and are unable to play the DTMF tone, you won't be able to check if it heard you correctly. In general though, you can use sip.cheogram.com to test out any SIP test service at least for audio.

I don't know of any way to test video calls, however. This is probably better discussed in the Dino MUC rather than here on the bugtracker.

**Comment by Symbian9** [comment]
> This is probably better discussed in the Dino MUC

What is that?

**Comment by licaon-kter** [comment]
@Symbian9 open xmpp:chat@dino.im?join from your XMPP client

**Comment by fiaxh** [comment]
I'm closing this since it's not a Dino issue.

I think this question might be better asked in some XMPP channel. I don't know of a test-room for video calls, but if you find one feel free to leave a message here. I'm sure others would love to know about it as well :slightly_smiling_face:
