### ISSUE TITLE
Dino is not displaying OOB previews

### ISSUE THREAD

**Issue by speedygonzales9** [dino/dino#1258]
Hi, 

In Dino, OOB [(XEP-0066)](https://xmpp.org/extensions/xep-0066.html) preview is ignored unless the whole body is a URL. I would like the preview thumbnails to display when I receive a message that includes OOB tags. Can you fix this issue please? 

Thank you

**Comment by speedygonzales9** [comment]
Another solution to fix this issue is https://github.com/xsf/xeps/pull/1188

**Comment by mar-v-in** [comment]
XEP-0066 defines two different "OOB" things:

`jabber:iq:oob`: An iq-based mechanism to ask the counterparts resource to download or open a URI (e.g. download file from http-URI or start call from sip-URI). I'm not aware of any popular client implementing this and we have no intention to support that protocol either.

`jabber:x:oob`: A tag that can be added to messages or presences to communicate a URI to another user or application. The exact behavior for what should happen with the communicated URI is left as an implementation detail. Dino supports parsing this tag in messages and considers messages a file transfer if the URI is an http(s)-URI and the same URI is also in the message's body. This behavior reflects what many other clients do. Any usage of oob beyond this poses the risk of causing problems with other clients.

To give you an example, the following would be a perfectly valid use of `jabber:x:oob`:
```xml
<message ...>
  <body>Do you know the band Systemabsturz?</body>
  <x xmlns='jabber:x:oob'>
    <uri>https://systemabsturz.band/</uri>
    <desc>Website of the band Systemabsturz</desc>
  </x>
</message>
```
If a client would consider this oob URI as a file transfer, this would likely cause a bad user experience (as they would downlad an html file rather than opening the website in their browser). Requiring body and oob tag to match severely reduces the risk of accidentally detecting a message containing an oob tag as a file transfer.

As such we don't plan to change the behavior to interpret oob tags beyond what we already do. We'll soon be supporting XEP-0447, which is planned to be updated to also support what you are looking for.

I don't understand how XEP-0428 would be relevant here.
