### ISSUE TITLE
False coloring of input chat field in dark themes

### ISSUE THREAD

**Issue by pizdjuk** [dino/dino#1315]
Dino release: 0.3.1

The reason is that textview background color is set to @theme_bg_color, which results in broken coloring of the input-field and unreadable input.

This patch corrects the behavior setting foreground color of textview and caret-color to @theme_fg_color

```
--- a/main/data/theme.css	2022-11-16 15:01:36.671785397 +0100
+++ b/main/data/theme.css	2022-11-16 14:58:03.497575921 +0100
@@ -207,6 +207,8 @@
 .dino-chatinput textview,
 .dino-chatinput textview text {
     background-color: @theme_bg_color;
+    color: @theme_fg_color;
+    caret-color: @theme_fg_color;
 }

```

**Comment by fiaxh** [comment]
The state you are working with does not seem to correspond to the theme.css in the Dino source code. [The respective code](https://github.com/dino/dino/blob/master/main/data/theme.css#L284) is (and has been since 2020):

```css
.dino-chatinput,
.dino-chatinput textview,
.dino-chatinput textview text {
    background-color: @theme_base_color;
}
```

Your patch claims that the current state would be `background-color: @theme_bg_color;` while it is actually `background-color: @theme_base_color;` . If you are working on top of a modified state, it might be that those modifications cause the issue in first place?

**Comment by pizdjuk** [comment]
it seems that I made a patch with wrong branch. The bug persists in the 0.3.1 release of dino (I didnt check the fresh git-version, but I suppose it is still there). So, the right patch should be

```
--- a/main/data/theme.css	2022-11-16 15:01:36.671785397 +0100
+++ b/main/data/theme.css	2022-11-16 14:58:03.497575921 +0100
@@ -207,6 +207,8 @@
 .dino-chatinput textview,
 .dino-chatinput textview text {
     background-color: @theme_base_color;
+    color: @theme_fg_color;
+    caret-color: @theme_fg_color;
 }
```

I attach the screenshot without a patch
![scr](https://user-images.githubusercontent.com/35386958/202238346-05580552-2316-4259-a381-151d381be91b.png)

**Comment by mar-v-in** [comment]
What theme are you using?
According to GTK specification, the foreground of a text entry and text content should be @theme_text_color and the background should be @theme_base_color. Setting it to @theme_fg_color is not intended here.
Also, I guess this is rather an issue in your specific GTK theme, because dark themes in general (like the official GTK dark theme) don't have any issues.

**Comment by pizdjuk** [comment]
Wow. I dont know why, but I was sure, that its not a theme issue. But changing theme results that it was.
Apologize for this inconviniece
