### ISSUE TITLE
Impossible to connect to ejabberd

### ISSUE THREAD

**Issue by liZe** [dino/dino#134]
When trying to connect to ejabberd, I get `Stream Error: mandatory-to-negotiate feature not negotiated` in the terminal. Did I miss something?

**Comment by fiaxh** [comment]
This surely isn't a problem with ejabberd in general. Unfortunately, this error alone does not sufficiently hint at the problem. Are there warnings or errors before that output? Are you maybe on a public server (and give me the address) so that I can simply look for the problem myself?

**Comment by liZe** [comment]
> Are there warnings or errors before that output?

No, there's nothing more.

```
(dino:24309): Gtk-WARNING **: Theme directory 256x256@2/animations of theme hicolor has no size field

Stream Error: mandatory-to-negotiate feature not negotiated
recovering in 3
```

> Are you maybe on a public server (and give me the address) so that I can simply look for the problem myself?

I'm on a private server, but I've created an account just for you: `dino@jabber.32rwr.info` (password: `dino`).

**Comment by fiaxh** [comment]
Thank you for providing the account, you can remove it again if you want.

The problem is that your server does not offer TLS to secure the connection. Dino does not attempt to send your login data over an unsecured connection. I would strongly advise you to correctly configure your server to use TLS.

It could be argued that it rather is a problem that your current client allows a connection. During a quick test, gajim and Conversations refused to connect to your server as well. What client are you using?

**Comment by liZe** [comment]
> The problem is that your server does not offer TLS to secure the connection.

Shame on me.

> What client are you using?

I'm using empathy and I don't have checked the option to allow unsecure connections. That's strange.

Thanks a lot!
