### ISSUE TITLE
OMEMO not working after copying omemo.db to a second machine

### ISSUE THREAD

**Issue by ehmry** [dino/dino#1353]
I copied my Dino state (.local/share/dino) from one machine to another and when running clients on both machines simultaneously the OMEMO messages would only be readable from one of two machines. Things are working fine after wiping the Dino state on one machine and generating new keys.

I would suggest that keys are locally bound to the hostname at generation time, but I'm not familar with OMEMO or the implemention of Dino.

**Comment by licaon-kter** [comment]
Well, you did something that was not meant to be done :)

What were you trying to achieve exactly? If you wanted to have the same account on the second device you should have just started Dino.

OMEMO keys are per device so chaos ensues when more than one device tries to use the same.

**Comment by ehmry** [comment]
I was worried that I would get this response. I wasn't trying to achieve anything unusual, this was a situation that arose out of normal backup-and-restore procedures. Copying home directories between machines is a normal thing to do, and if and application breaks because of it then the problem is with the application and not me.

**Comment by licaon-kter** [comment]
"Backup and restore" means ONLY one device runs the same setup, you backup the old, you purge the old, you restore on new, you carry on.

/close as invalid

**Comment by ehmry** [comment]
A home directory can also be on a shared network filesystem. Applications developers can't dictate what users do with their files or define what a backup is or isn't.

I opened this issue because I had a problem and I wanted to see Dino improved. After reading previous issues and this experience I can't keep using it.

**Comment by licaon-kter** [comment]
Not sure I follow, you broke the encryption by "using the device key simultaneously on more devices".

How is Gajim handling this exactly? How is Psi+?

**Comment by ehmry** [comment]
I didn't say any app was bad, it's your reaction that I have a problem with.

**Comment by ehmry** [comment]
Oops, I didn't realize @licaon-kter is a nobody troll, I thought they were a contributer.

**Comment by licaon-kter** [comment]
'Course I am whatever you want me to be. That doesn't make me wrong though. ;)

**Comment by Aman9das** [comment]
> but I'm not familar with OMEMO

**Comment by mar-v-in** [comment]
Hi @ehmry.

OMEMO identities and sessions are meant to be "device-specific" and should generally not be copied from the system to anywhere else. This is a restriction coming from the cryptographic properties of the Signal protocol and nothing we can change.

However, some usecases that involve copying (even if not intended by the protocol) can still be supported and we selected to not support your usecases over not supporting others.

What we can do is:
- Allow users to *move* a Dino instance from one computer to another (already supported)
- Allow users to run Dino with a user profile on a network drive for as long as the user does not log in to his user profile on multiple computers at the same time (already supported)
  - Attempts to do the latter can be detected and blocked
- Allow users to restore an older state from a backup, while loosing messages sent since the time of the backup. (not yet properly supported)
- Allow users to change their system configuration (incl. mac address) while using Dino.

What we can't do is:
- Allow users to *clone* a Dino instance to a second computer (one-way clone)
- Allow users to keep two Dino instances in sync while using both and the same time (two-way sync)

What is generally impossible:
- Allow users to restore an older state from a backup and recover messages since the time of backup

While you are right that tying the omemo database to the mac address would solve your use case of one-way clone and could even allow for two-way sync, it would still mean that the two computers use different identities and sessions. This means that if users are verifying each others identity keys, this would still break as the identity key of the clone would not be verified after cloning. (Also, there are usecases where mac address detection is not possible, for example when Dino is run in a sandbox).

At the same time, doing so would break identity verifications in many of the already supported usecases, as they may include a change of mac address (e.g. multiple computers accessing the same home folder from a network drive would typically have different mac addresses). So the best thing that remains for your advanced usecase is to ask advanced users to not include the `omemo.db` when cloning or two-way synchronizing home folders across computers. From beginners we generally do not expect them to touch their `.local` (it's hidden after all).

And because there are some culprits to doing this depending on your server, we generally advice users to not duplicate their database at all and officially only support moving usecases, see [How to move the data and configuration?
](https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)#how-to-move-the-data-and-configuration).

I hope this helps understanding why we don't and won't support your usecase.
