### ISSUE TITLE
No more gray icons for unavailable contacts

### ISSUE THREAD

**Issue by Kobaxidze256** [dino/dino#1403]
I can't see gray icons for unavailable contacts after recent upgrade to either 47a06698 or at least 65efaca6.

**Comment by mar-v-in** [comment]
In fact this is since commit db3b0d5f233ee3587ae54f8f035222cb098b11dd. It is intentional, as we don't plan to gray the avatar anymore to indicate online status. The reasoning here is that avatars may be grayscale, making the indicator unusable for those contacts. On top, many users are always-online due to the usage of smartphones.

For now, the only way to see if a contact is online is by hovering over the contact in the sidebar and see if the tooltip shows any online devices. This also allows you to see the kind of device and - if sent by the contact's app - if contacts are away from their device. In the future we probably will add a more convenient way to do this.
