### ISSUE TITLE
Avoid avatar download for spam protection

### ISSUE THREAD

**Issue by ghost** [dino/dino#1415]
Request to store *Avatars* & *Files* cache in `.cache` instead of the same directory `.local/share` in future releases.

**Reasoning**
This makes it easier for Tails users to not persist this cache or really anyone that doesn't want to store random peoples automatically downloaded avatars or files they opened in rooms (mucs) to their disc. If there is a work around it should be documented in the *Wiki*.

- **Edit (4/6/23):**

Title changed from *Move Avatars and Files folders to ~/.cache* to: 

## Avoid avatar download for spam protection

*Feature Request*

Option in settings/toggle saying "Show avatars" for the user to disable/enable automatic downloading and fetching of avatars of users in public mucs. Upon switching the option off would clear the current stored avatar cache.

##  Reasoning like also mentioned is that *Avatars* are automatically fetched to the users disk.

 **1.** *Security*

- The *hypothetical* possibility of a "zero day" exploit executed by [GdkPixbuf](GdkPixbuf) or how [Dino renders avatars](https://github.com/dino/dino/blob/master/main/src/ui/widgets/avatar_picture.vala#L288) in the future as mentioned by @sandwm. (There is no known vulnerabilities that I or anyone knows of at this time)
		
**2.** **Protection from spammers with illegal, questionable, or offensive pictures as avatars** 
	
- This one seems most reasonable as a spammer/s could have illegal images (CSAM) as their avatar and xmpp users would unknowingly download these to there disk since clients automatically download avatars of joined mucs to disk cache. This is more of a valid point and I don't think anyone wants this happening to them.

	### Possible Solution
	
- Something maybe along the lines as rendering an empty element for vCard photos set as users avatars.

[Dino Supported-XEPs](https://github.com/dino/dino/wiki/Supported-XEPs)

[XEP-0084: User Avatar](https://xmpp.org/extensions/xep-0084.html)

[XEP-0153: vCard-Based Avatars](https://xmpp.org/extensions/xep-0153.html#publish)

**Comment by sandwm** [comment]
I think ~/.cache is for data that could be re-created on demand (only cached/stored here for performance or similar reasons) and/or would be no actual loss if missing. That does not apply to files sent to me by other people. I might want to see those (images, PDFs, whatever) again at a later time, but the XMPP server probably won't store them for an unlimited time. So storing those files in ~/.cache and then clearing that folder would mean losing them. Probably not an issue in all cases, but in some indeed.

For avatars ~/.cache might be fitting. The current ones should be able to be retrieved again from the server.

**Comment by sandwm** [comment]
Do you want to move the avatars to ~/.cache for saving disk space, e.g. because you often join and leave different, large MUCs (small ones shouldn't make much of a difference - the avatars I have in ~/.local/share/dino/avatars/ are around 10KB per avatar)? Or do you see this as a security precaution? Because I don't see how it would make much sense in the latter case. If the files are opened, it doesn't make a difference whether they are downloaded again or just loaded from disk. And if they just lie around on disk, not being used, they don't do anything.

> The biggest benefit/strength of most XMPP clients like dino is that they don't have automatic previews or autmatic downloads turned on which means not downloading any files shared in public group chats (mucs) without clicking to do so... But XMPP clients still download avatars but I don't think that is bad as files but maybe i'm wrong.

Um, dino actually does automatically show images sent in chat rooms. (At least the ones I am part of, but I don't think there would be a difference for different kinds of rooms.) I don't know whether that was already the case in version 0.2.0 if that is what you are using (a quick search says the current Tails [gets its software from Debian 11 (bullseye)](https://tails.boum.org/doc/about/features/index.en.html) which [has Dino 0.2.0](https://packages.debian.org/search?keywords=dino-im&searchon=names&suite=all&section=all)), but current versions do that. What version do you have?

However, whether it's an image sent as part of a chat or as an avatar probably doesn't make much of a difference, since (I think) both would be rendered using the same software: [GdkPixbuf](https://gitlab.gnome.org/GNOME/gdk-pixbuf), which is the standard image loader for GTK-based applications like Dino. (For avatars, it's used [here](https://github.com/dino/dino/blob/master/main/src/ui/widgets/avatar_picture.vala#L288).) So rendering images by default probably doesn't open up a new security hole, compared to doing the same for avatars.

Other files (PDFs, ...) are still left untouched (i.e. no preview or similar) until explicitly opened.

> Sadly many other chat applications (non xmpp jabber) do have them turned on from what I know which is a weakness and how pegasus was exploited.

If you are referring to NSO's Pegasus, that is a software that abuses more than just one exploit. The one I remember is the [zero-click iMessage exploit](https://googleprojectzero.blogspot.com/2021/12/a-deep-dive-into-nso-zero-click.html). That one was ingenious in how it was created – and awful for what it was used... It abused some particularities of the image format JBIG2, which (fortunately) I don't think are mirrored in any modern image formats / those supported by GdkPixbuf. (Doesn't mean GdkPixbuf is 100% secure, but nothing is. If you are really interested, dig into what formats it supports itself or through the loaders found below /usr/lib/gdk-pixbuf-2.0/.)

**Comment by sandwm** [comment]
> The biggest thing that bothers me is spammers setting illegal or questionable pictures as their avatars. Since avatars are automatically fetched to disk, one could have illegal bytes on their own disk and may not know it. [...]

That could theoretically happen with probably almost any messenger out there, as well as caches of web browsers, things hidden in email attachments etc. It would be very absurd to prosecute someone for having on disk cache the avatar image of a different person who just happened to be in the same big group chat as you. A bit like saying "don't use any Internet service at all". As long as you don't upload those folders to (CSAM scanning and automatically banning) cloud storage or similar, I wouldn't worry about that (and I'm usually a very cautious person in regards to IT).

> Also from what I know is clients do not remove metadata from sent files so I would assume that avatars stored on JID server don't remove the metadata either. Which mean any payload attached maybe could be executed maybe? [...]

If you are talking about metadata included within image files, like [Exif](https://en.wikipedia.org/wiki/Exif): Those can contain information about the camera used to take the photo, data about the image itself (resolution etc.), date and time, location, a thumbnail and more – or much less than that, depending on what the camera / software did or did not include. But they don't include executable code.

If you are talking about metadata like [in XEP-0084](https://xmpp.org/extensions/xep-0084.html#proto-meta) you referenced or the vCard data [in XEP-0153](https://xmpp.org/extensions/xep-0153.html#publish), then again: there is no executable code. This is just XML data, which is what XMPP is based on.

So no, unknown security bugs notwithstanding, Dino won't execute code from any images received as avatars or elsewhere. (And the part of "unknown security bugs notwithstanding" applies to literally any data Dino has to work with, even the most basic XMPP elements. I don't see a really significant risk increase here for the avatar images.)

In the end, it's up to the maintainers to decide whether to implement or accept a pull request for something like you requested. I initially only answered because of the sent-files-in-cache thing. However, I don't think the chances of it being implemented are high, because the complexity introduced would outweigh the potential benefit and Dino seems more to follow a simplistic approach (which by reducing complexity is actually good for security) than a "there's a setting for everything"-approach like e.g. Gajim.

**Comment by fiaxh** [comment]
Avatars are stored in ~/.cache as of https://github.com/dino/dino/pull/1621.

Regarding disabling avatars in order to protect from spammers: Perhaps we can solve this in a different way: When someone is banned from a channel, remove their avatar from the cache. That way, users still have the feature of avatars, while potentially harmful avatars are removed.
