### ISSUE TITLE
If you use it with fcitx5, a strange bug will appear.

### ISSUE THREAD

**Issue by TechnicalSuwako** [dino/dino#1419]
fcitx5で使ったら、変なバグが出ます。
特にまずはローマ字で入力して、IMEを有効にして、日本語で入力して、メッセージを送る前に日本語入力を終わるにはEnterキーを押すと、直ぐローマ字部分だけが送られます。
動画→ https://ass.technicalsuwako.moe/2023-04-0222-03-22.mkv
バグはバージョン0.4.xだけで発生されます、0.3以前は問題なかったのです。

Machine translation:
If you use it with fcitx5, a strange bug will appear.
In particular, if you first enter in romaji, enable the IME, enter in Japanese, and press the Enter key to end the Japanese input before sending the message, only the romaji part will be sent immediately.
Video → https://ass.technicalsuwako.moe/2023-04-0222-03-22.mkv
The bug only occurs in versions 0.4.x, 0.3 and earlier were fine.

**Comment by haansn08** [comment]
I also have this problem. I think the reason is Dino somehow catches the <kbd>Enter</kbd> key before the IME does. This bug renders Japanese input almost impossible.

A workaround is to use <kbd>Ctrl</kbd>+<kbd>M</kbd> for every conversion commit, but if muscle memory has commit on <kbd>Enter</kbd> it is infuriating. If you cannot imagine how infuriating this would be to a Japanese user, try getting used to pressing <kbd>Ctrl</kbd>+<kbd>M</kbd> instead of <kbd>Space</kbd> after every word.

**Comment by fiaxh** [comment]
This should be fixed on master now, and we will include the fix in the next bugfix release. Please feel invited to verify that it actually solves your usecase.

**Comment by haansn08** [comment]
I can confirm this commit fixes the issue for me.
