### ISSUE TITLE
Reply-to fallback character counting issue with non ASCII chars

### ISSUE THREAD

**Issue by truenicoco** [dino/dino#1420]
I think dino does not count code points correctly, see these two (partial) stanzas sent by dino:

```xml
<body>&gt; base
bose</body>
<fallback xmlns="urn:xmpp:fallback:0" for="urn:xmpp:reply:0"><body end="7" start="0" />

<body>&gt; bäse
bose</body>
<fallback xmlns="urn:xmpp:fallback:0" for="urn:xmpp:reply:0"><body end="8" start="0" />
```

Changing `a` to `ä` made dino count an extra character, but I don't think that's conform to [XEP-0426](https://xmpp.org/extensions/xep-0426.html)

**Comment by singpolyma** [comment]
I ran into this today too, dino seems to both send and receive counts in bytes rather than in codepoints.

**Comment by Zash** [comment]
![image](https://user-images.githubusercontent.com/197474/235295656-16e8705a-b3d8-4c1e-9380-56a34dd91eca.png)

Replying to messages with a trailing emoji seems to prevent the reply from rendering, possibly because the emoji gets cut in two and some invalid UTF-8 is produced. In the above screenshot, they replied with "Reply", but this is nowhere to be seen.

**Comment by singpolyma** [comment]
@fiaxh thanks for this, it seems I am using java code units instead of code points. will fix
