### ISSUE TITLE
Remove JS from site

### ISSUE THREAD

**Issue by serfcity** [dino/dino#1436]
https://dino.im haven't got dynamic content. Please remove JS from site.
It will be cool if you use XHTML 1.0 Strict instead of HTML5 and use CSS2 instead of CSS3.
This site is primitive, but not "KISS". We can make Internet clearly!

**Comment by mar-v-in** [comment]
- The JavaScript on our page is entirely optional and only provides minor quality of life improvements. Using the page without scripts is supported just fine and will continue to be supported in the future.
- XHTML 1.0 Strict and CSS2 lacks a lot of important features, like proper support for viewport handling and media queries as well as improved accessibility. Without HTML5/CSS3 we would not be able to provide a website with decent user experience to mobile users.

**Comment by serfcity** [comment]
Web-server can respond differently for mobiles and desktop clients.
Just select version of web-site by user-agent.

**Comment by mar-v-in** [comment]
> Web-server can respond differently for mobiles and desktop clients.
> Just select version of web-site by user-agent.

That's a terrible idea.
- You're relying on users sending you information that you wouldn't need to process otherwise.
- This means that the website can't be efficiently cached and delivered through static file servers.
- User-Agent lacks sufficient information to optimize for various form factor. You are not guaranteed to reliably differentiate between a desktop computer and a phone, let alone the various form factors in between.

**Comment by serfcity** [comment]
In this case user can permanently setup version of the web-site.
For example www.m.dino.im for mobile devices and www.dino.im for PCs.

**Comment by mar-v-in** [comment]
That's not the user experience we intend to provide.
