### ISSUE TITLE
Dino can't handle duplicate JID resource part

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#1623]
Dino seems to randomly generate the resource part of the JID and store it in the `accounts` column of `dino.db`. I think it has 4 bytes of randomness in it, which is probably sufficient, but might cause collisions. Collisions can also happen is a user copies the dino database onto another machine.

It would be best if Dino has a way to detect a duplicate resource part and simply re-generates a new one.

This has been the root issue of at least one occurrence of https://github.com/dino/dino/issues/896, that I manage to solve by manually changing the resource part.

**Comment by stevenroose** [comment]
To be honest, the resource part is kind-of a privacy leak, so there is no hurt in Dino regenerating a new one as much as it is not impractical to do. So even if a new one is generated every startup, it would be better for privacy IMO. Also, it should probably not include the name `dino` as this also reveals your client to your conversation partners.

**Comment by stevenroose** [comment]
Not sure if some of the OMEMO stuff is based on full JIDs and if that can/will cause issues if they are randomly cycled.

**Comment by fiaxh** [comment]
Dino will now regenerate the resource when it is disconnected due to a resource collision (4d4ba7dde6d3153fa5ea652a8b37d7b78f511484).

As for privacy implications of the resourcepart: Removing "dino" from the resource, won't hide the client's identity, as there are many factors that can be used for client identification. I gave some examples in https://github.com/dino/dino/issues/954#issuecomment-739546535.

Every client I know of generates the resource as Dino does, including keeping it stable between reconnects. The latter is also recommended on modernxmpp.
