### ISSUE TITLE
Allow to scale icons on HIDPI screens

### ISSUE THREAD

**Issue by catap** [dino/dino#1635]
GTK respects `Xft.dpi` out of the box and scales fonts and it works like a charm. But it doesn't scale icons. See: https://gitlab.gnome.org/GNOME/gtk/-/issues/4528

As result my UI looks like:
![image](https://github.com/user-attachments/assets/b045e723-959b-4b65-898d-7b536be9b514)

**Comment by mar-v-in** [comment]
`Xft.dpi` is for scaling fonts, not for display scaling you'd want for HiDPI purposes. Thus, this result is expected, as is also mentioned in the issue you linked. While it seems to do the expected scaling for many apps, this is only coincidental, as many user interface elements are designed to fit the font. It's not the same and can also be seen with paddings, rounded corners, displayed pictures and other UI elements. For example, in your screenshot, even if the icon size was increased, the paddings, line width and border radius of the surrounding box would still remain as is and thus not as expected.

Display scaling should be done per display, using xrandr or using the monitor section of your Xorg configuration. Alternatively you can also scale GDK applications globally using `Gdk/WindowScalingFactor` xsettings configuration (and if that causes fonts to be scaled twice, you can set `Gdk/UnscaledDPI` to override `Xft.dpi` for apps that understand `Gdk/WindowScalingFactor`.

**Comment by catap** [comment]
@mar-v-in well, here an issue: Chrome has expected size of its UI and usually other software which includes Gajim which is Gtk base as well.

**Comment by mar-v-in** [comment]
As I said, some user interface elements may coincidentally match the font size and thus look as expected or similar to expected. Some applications also might consider screen scaling and font dpi to be the same thing and just/or just work based on one of them.

GDK has support for display scaling built-in, so there is nothing we should be doing from application side. The icons you picked are not the only icons or user interface elements that currently don't scale with the font, adding manual support for this everywhere when the toolkit can already do it when configured correctly is unreasonable work for us. On top, every attempt to do manual scaling of this is likely going to be half-complete and cause issues for users where everything works correctly (because they set up their environment as necessary), e.g. when handling multiple screens with different display scaling.

**Comment by catap** [comment]
Indeed:
```
~ $ cat .config/gtk-4.0/gtk.css      
* {
    -gtk-icon-size: 8pt;
}
~ $ 
```
makes what I'd like.
