### ISSUE TITLE
Please add spell-checking support

### ISSUE THREAD

**Issue by ThibG** [dino/dino#186]
Please add a way to spell-check the user's message, as other XMPP clients do.

**Comment by bochecha** [comment]
As a data point, I guess the right library here would be [gspell](https://wiki.gnome.org/Projects/gspell)?

**Comment by akhilman** [comment]
Is there any reason not to use [GspellEntry](https://developer.gnome.org/gspell/stable/GspellEntry.html) instead of [GtkTextView](https://github.com/dino/dino/blob/5d65f047d0fd1a1ed4a3bbe076d5cb4df76e7d5f/main/data/chat_input.ui#L53) for text input?
GspellEntry also will support GTK's emoji input (Ctrl+Shift+E).

**Comment by donpatrice** [comment]
Any news about that feature?

**Comment by fiaxh** [comment]
This feature has been added in #317.
