### ISSUE TITLE
[roster] display roster stored in jabber profile

### ISSUE THREAD

**Issue by arthurlogilab** [dino/dino#189]
Am trying to switch from pidgin, and am finding a few things great, and a few things a bit missing. 

Would it be possible to display the roster I have configured (which I believe is stored on the jabber/xmpp server) by default instead of having to add individually each person I want to chat to ?

**Comment by d9h20f** [comment]
Do you mean that all contacts should be displayed in the main window, regardless of whether you have any conversations with them or not, like in Signal's desktop client?

**Comment by arthurlogilab** [comment]
@d9h20f in pidgin I had configured to display all online contacts, then I had groups (which I think are stored only in pidgin, not in roster) so I could "hide" contacts less important or frequently used. Sorry I don't know Signal's desktop client.

**Comment by fiaxh** [comment]
Dino implements a conversation list (right side in the main window) in which open conversations are displayed. You can access the contacts in your roster from [+] > AddChat and start conversations from there. The conversation list "hides" less important people automatically, because the conversation list is sorted by date.
