### ISSUE TITLE
Fix joining of manually entered MUC on startup

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#24]
As written in https://github.com/dino/dino/issues/3#issuecomment-286355143, dino doesn't rejoin a manually joined MUC on startup. I can type messages in the MUC and they appear to be sent, but nobody else can see them, and vice versa.

**Comment by fiaxh** [comment]
The joined MUCs are now synchronized with the `autojoin` flag in the bookmarks:
- Joining a MUC (creates a bookmark and) sets `autojoin=true`, parting it sets `autojoin=false`
- If a bookmark has `autojoin=true` but is not joined, it is joined. If it has `autojoin=false` but is joined, it is parted. Using pubsub instead of (additionally to) private XML for bookmark storage would improve this behavior.

Among others, this resolves this issue.
