### ISSUE TITLE
Reword "JID" to ....?

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#375]
What is a JID? Can we please rename it to Jabber ID?

thanks.

![image](https://user-images.githubusercontent.com/26681446/40773695-f6a32bbe-64c3-11e8-9cf1-c035697bff26.png)

**Comment by licaon-kter** [comment]
I'd like "XMPP Address" instead, see https://github.com/dino/dino/pull/710#issuecomment-571174912

**Comment by j-cr** [comment]
Note that "jid" is a racial slur for jews in russian and other slavic languages. Rename ASAP (make those CoCs actually useful once in a while please).

+1 for any of the following: ID, XMPP ID, XMMP Address (also XMPP Login, Login). Personally I prefer "ID" since it's shorter and doesn't confuse the user with weird acronyms.

Note that in this particular screenshot the reporter provided there's another potentially confusing detail: the title says "Add Contact", but in the form itself there's no mention of the word "Contact". Also, since most messengers either don't have the concept of multiple accounts or have the default "current" account, the drop-down list named "Account" in the "add contact" dialog can be potentially confusing for newbies: «I wanna add friend@foo.org account to my contacts, but in the add contact dialog it only shows my@foo.org account; by the way what the hell is 'jid'?!»

Thus my suggestion is to have exactly one input field in the "Add Contact" dialog, and hide the account selection menu by default:

```
+------------------------------+
| [Cancel]  Add Contact  [Add] |
+------------------------------+
|                              |
| Contact ID: [______________] |
|                              |
+------------------------------+
| VVV use another account? VVV |
+------------------------------+
```

**Comment by licaon-kter** [comment]
But which account @j-cr is default? I'd like to see which one...

**Comment by jcbrand** [comment]
FWIW Conversations and Converse.js use "XMPP Address" which I see as similar to "Email Address" which people are already used to.

"Jabber" is a registered trademark and for that reason alone I don't want to use it in Converse.js.

**Comment by j-cr** [comment]
@licaon-kter I don't know. Obvious options: the one that was used last or the one that is explicitly marked as 'default'. Other messengers often have the concept of the "current" account, though going that route probably would mean that you can't use 2+ accounts at once, which is suboptimal (even if newb-friendly).

In general, I find the support for multi-account setups is lacking in Dino (for example, in roster there's no way to tell apart two dialogues from different accounts with the same target); thus there's definitely room for improvement in UX in this respect. That's a different issue altogether though.

**Comment by singpolyma** [comment]
"Jabber ID" is the correct full name used in all XMPP documentation.  I agree that the full name is less ambiguous than "JID".

**Comment by Zash** [comment]
[Modern XMPP](https://docs.modernxmpp.org/), a project with the goal of improving consistency among all XMPP clients, currently recommends [_Address_ or _XMPP address_](https://docs.modernxmpp.org/terminology/)

**Comment by Trendyne** [comment]
I'd also like to be able to translate it to something saner

> Note that "jid" is a racial slur for jews in russian and other slavic languages

I think JID would be more like Джид than Жид in Russian, no?

**Comment by fiaxh** [comment]
The JID is now called "XMPP address" everywhere in the UI.
