### ISSUE TITLE
Use meson build system

### ISSUE THREAD

**Issue by tintou** [dino/dino#396]
It's fast, has great Vala support and is now the default build system for GNOME

**Comment by dos1** [comment]
While I fully understand and support migrating from autotools to meson, Dino already uses CMake, which is just fine.

**Comment by BaptisteGelez** [comment]
Hello! I would like to know if you would accept a PR that adds meson as a build system (and that removes CMake if you don't want to maintain both)? I've heard from some other contributors that using CMake was not that easy for them, and it probably discourages some people from contributing.

**Comment by selurvedu** [comment]
JFYI, both https://github.com/benwaffle/vala-language-server and https://gitlab.gnome.org/esodan/gvls do not work without Meson build files. As a result, the code editor of GNOME Builder is unusable because it [relies on GVls](https://blogs.gnome.org/despinosa/2020/03/02/gvls-0-14-0-released/) for finding symbols.
Also, the run / debug feature [does not support CMake](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/498#note_631144), so using Builder as a frontend for gdb is not possible as well:

> We do have minimal CMake support, but it lacks run support (unless you're using Flatpak) due to deficiencies in extracting runnable executables from CMake. It's decidedly low priority for us because GNOME doesn't use CMake.

I'm not saying that CMake should be dropped in favour of Meson. I'm just sharing my findings to help anyone who bumps into similar issues with Vala language servers and/or GNOME Builder.

**Comment by Prince781** [comment]
As the developer of VLS, I think you guys should check out https://github.com/Prince781/vala-language-server/issues/73 and give your input. It's possible that if you change your CMake-Vala addon code to use `add_custom_target()` instead of `add_custom_command()`, the language server would be able to work with your project. I don't know much about CMake though so your input is appreciated.

**Comment by sojuz151** [comment]
My personal solution for using Vala language server is generating simple meson.build, good enough to get autosuggestion working. You need to copy some files so I created a python script for this. It works good enough 
```
#!/usr/bin/env python3
from pathlib import Path
subprojects = ['crypto-vala','libdino','main','plugins','qlite','xmpp-vala']
sources = []
customVapis = []
for sp in subprojects:
    for path in Path(sp+"/src").rglob('*.vala'):
        sources +=  ["'%s'"%(str(path))]
    for path in Path(sp+"/src").rglob('*.vapi'):
        customVapis +=  ["'%s'"%(str(path))]       
buildFiles = open("meson.build","w")
buildFiles.write(""" 
project('xmpp-vala', 'vala', 'c','cpp')
dependencies = [
    dependency('gdk-pixbuf-2.0'),
    dependency('gee-0.8'),
    dependency('glib-2.0'),
    dependency('gio-2.0'),   
    dependency('gobject-2.0'),
    dependency('harfbuzz-icu'),
    dependency('libgcrypt'),
    dependency('libsrtp2'),
    dependency('gtk+-3.0'),   
    dependency('gstreamer-1.0'),
    dependency('gstreamer-video-1.0'),
    dependency('gspell-1'),
    dependency('sqlite3'),
    meson.get_compiler('vala').find_library('emojichooser',dirs:  meson.current_source_dir()/'main/vapi/'),
    ]    """)
buildFiles.write("\nsources = files(%s)"%",\n".join(sources))
for sp in subprojects:
    buildFiles.write("\nadd_project_arguments(['--vapidir', meson.current_source_dir()/ '%s/vapi'], language: 'vala')"%sp)
for vapi in customVapis:
    buildFiles.write("\nadd_project_arguments(['--vapi=', meson.current_source_dir()/ %s], language: 'vala')"%vapi)
buildFiles.write("\nexecutable('Dino', sources,dependencies: dependencies)")
buildFiles.close()
cv1 = open("xmpp-vala/vapi/harfbuzz-icu.vapi","w")
cv1.write(open("xmpp-vala/vapi/icu-uc.vapi").read()+open("main/vapi/icu-uc.vapi").read())
cv1.close()
cv2 = open("crypto-vala/vapi/libgcrypt.vapi","w")
cv2.write(open("crypto-vala/vapi/gcrypt.vapi").read())
cv2.close()
```

**Comment by Prince781** [comment]
Just to link to what I was talking about in a previous comment:

https://github.com/Prince781/Vala_CMake/commit/1620ef40f523a12dae988f2c06edbbacf3ac604a

**Comment by eli-schwartz** [comment]
It seems this project has rather a lot of custom code to find dependencies, e.g. `find_pkg_config_with_fallback` for all sorts of gnome libraries.

This is frankly not very idiomatic even for cmake, because you can use `IMPORTED_TARGET GLOBAL`. Of course you claim to support cmake 3.3 and neither one is available in cmake versions that old.

On the other hand, not only is pkg-config a first class citizen in meson (it is NOT a first class citizen in cmake), many of your dependencies also use meson, and meson allows you to trivially embed other meson projects as subprojects with linux distro-friendly fallbacks from system versions. The neat thing is that building subproject fallbacks for system dependencies doesn't even require editing your build description, merely adding an ini file to the `subprojects/` directory.

As it seems there is some interest by users in having an appimage or flatpak of this project, being able to throw a configuration switch and force building most/all dependencies as private (static!) copies may be of some use.

**Comment by lockywolf** [comment]
I would like to try to contribute to Dino a bit, and this issue is a nuisance. Indeed, very few Vala projects use CMake, and Dino's way of launching cmake via "configure" is not very flexible. So I would support this issue.

**Comment by fiaxh** [comment]
#1453 added meson support.

**Comment by onion108** [comment]
> As the developer of VLS, I think you guys should check out [vala-lang/vala-language-server#73](https://github.com/vala-lang/vala-language-server/issues/73) and give your input. It's possible that if you change your CMake-Vala addon code to use `add_custom_target()` instead of `add_custom_command()`, the language server would be able to work with your project. I don't know much about CMake though so your input is appreciated.

It seems the current version still don't work with `vala-language-server`. It's complaining about lacking `version.vala` and I can't figure out why after reading meson.build multiple times.

<img width="1440" alt="スクリーンショット 2024-11-25 11 34 52" src="https://github.com/user-attachments/assets/becaa013-434d-47ef-b153-afab8faacef4">

I cloned repository of `vala-language-server` and runs the language server on the project and it works find. I found that `vala-language-server` uses `vcs_tag` to generate `version.vala` while this project uses a python script and a custom target. Still can't figure out what exactly are the differences tho.
