### ISSUE TITLE
Provide more binaries

### ISSUE THREAD

**Issue by mray** [dino/dino#43]
I know it is extra work, but think having an issue makes sense:
I'm on Ubuntu and would *love* to give Dino a try - it sounds and looks amazing!
I'd also love a standalone executable outside repositories for now.

**Comment by jubalh** [comment]
People who want to use a program should wait until its finished, released, packaged.
If they run into problems they can't do anything anyways.

Developers and tester usually know how to get the sources and build them.

Since GitHub is around everybody writes issues like this everywhere :-) Seems like bugzilla  had its nice sides after all hehehe.

**Comment by mray** [comment]
Unless you think there are enough binaries all you just did is spending developer attention and time to read your sad rumbling.

There is nothing that fosters a great community like a warm welcome like this. Shame on you.

**Comment by fiaxh** [comment]
I had to look through many pages of adorable owl pictures in order to close this issue. Don't make me do that again.
(more packages see #22; executable: probably not)
![](https://i.imgur.com/4INPTkO.png)
