### ISSUE TITLE
segfault when run with libsignal-protocol-c

### ISSUE THREAD

**Issue by bowlofeggs** [dino/dino#485]
Greetings!

I've been working on packaging dino for Fedora, and ideally I'd use a system provided ```libsignal-protocol-c``` instead of the bundled version.

I made a package for ```libsignal-protocol-c-2.3.2``` (the latest release), but when I link dino against that package it segfaults if I send a contact an OMEMO encrypted message.

I see that dino's bundled version is a commit that is a few after the 2.3.0 release, so I guess it's possible that dino is not compatible with 2.3.2?

I can bundle this dependency in Fedora if need be, but I thought it would be worth reporting here. I may be able to just ship 2.3.0 in Fedora instead, though I'd prefer to use the newer version if possible.

**Comment by bowlofeggs** [comment]
I packaged ```libsignal-protocol-c-2.3.0``` and the segfault went away, so I suppose there must be some incompatibility with the newer release of ```libsignal-protocol-c```.

**Comment by mar-v-in** [comment]
@bowlofeggs this is because of https://github.com/signalapp/libsignal-protocol-c/issues/112. OpenSUSE packages also already had this problem, their solution was to statically link the old version into dinos omemo plugin (which is already supported by our build script). Upstream seems to be not very sensible about third-parties using their library, so this seems for now to be the best thing possible. We might switch over to support 2.3.2 at some point or use a different library once a suitable one becomes available.

**Comment by mar-v-in** [comment]
We are using libsignal-protocol-c 2.3.2 since commit 7012023. Closing this now.

**Comment by bowlofeggs** [comment]
Whoah that was quick, thanks!
