### ISSUE TITLE
Is zh_Hans a valid locale name?

### ISSUE THREAD

**Issue by bowlofeggs** [dino/dino#524]
Greetings!

I've been working on [packaging dino for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1674181), and one problem the [reviewer pointed out](https://bugzilla.redhat.com/show_bug.cgi?id=1674181#c5) is that the zh-Hans locale is getting installed to ```/usr/share/locale/zh_Hans``` instead of ```/usr/share/locale/zh-Hans```.

I don't know much about localedata - do you know if it should have that dash in it instead of the underscore?

**Comment by bowlofeggs** [comment]
I posted this question on Fedora's devel mailing list too in case someone on there knows:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/OZEZYC67QOA4J7R4K3UEPAD3VP3BRJAC/

**Comment by bowlofeggs** [comment]
I've come to learn that Fedora's rpmlint is equally upset with a dash instead of an underscore, so I think that might not be the key. Perhaps the suggestion on devel list to add a CN on the end (or some country) is really what's needed?

**Comment by bowlofeggs** [comment]
One suggestion in the Fedora devel thread is to use zh_CN. What do you think about that?

**Comment by pnemade** [comment]
I found that as this project is using Weblate and they have the language list at https://hosted.weblate.org/languages/ and https://hosted.weblate.org/languages/zh_Hans/#information

So zh_Hans is coming from Weblate actually. Maybe this project can fetch zh_Hans translations and have some way to map or move zh_Hans.po to zh_CN.po

**Comment by tonghuix** [comment]
I am the translator working on zh_CN. If I remember is correct, zh_Hans coming from Mozilla project, cause China, Singapore and Malaysia using Simplified Chinese. However, zh_CN, zh_SG has two different locals and have to maintain two translation team.  But I don't like zh_Hans, it simplified translation, but others not, such us currency. And further more, Chinese we use in China, in Singapore and Malaysia has little difference, like different character, which can not be merged into one.

So I suggest using zh_CN instead of zh_Hans.

**Comment by github-k8n** [comment]
Agreed, maybe just split zh_Hans into zh_CN and zh_SG,
and zh_Hant into zh_TW, zh_HK, and zh_MO
as a first basis, then small differences can be fixed later on..  (and remove zh_Hans and zh_Hant, as locale it is useless.)

zh_CN 	Chinese (Simplified, PRC)
zh_SG 	Chinese (Simplified, Singapore)
zh_TW 	Chinese (Traditional, Taiwan)
zh_HK 	Chinese (Traditional, Hong Kong S.A.R.)
zh_MO 	Chinese (Traditional, Macao S.A.R.)
