### ISSUE TITLE
ArchLinux package needs a rebuild

### ISSUE THREAD

**Issue by loupianche** [dino/dino#543]
$ dino 
dino: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory

$ ls -l /usr/lib/libicuuc.so.64
lrwxrwxrwx 1 root root 16  4 avril 22:26 /usr/lib/libicuuc.so.64 -> libicuuc.so.64.1

**Comment by jubalh** [comment]
The one in AUR or OBS?

**Comment by loupianche** [comment]
AUR packages are source packages so the one in OBS :-)

**Comment by ChronosX88** [comment]
Same problem on Manjaro Linux

**Comment by loupianche** [comment]
Should be cool to have dino in Flathub :-) #453

**Comment by fiaxh** [comment]
The OBS package has been rebuilt.

**Comment by PolynomialDivision** [comment]
Have the same issue.
But the library should be changed to `libicuuc.so.65`?

**Comment by fiaxh** [comment]
@PolynomialDivision The OBS package has been rebuilt, that should solve your problem.

**Comment by LinuxCuba** [comment]
I have the same issue in KaOS Linux.
linuxcuba  ~  dino
dino: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
linuxcuba  ~  find / -name libicuuc.so.* 2>/dev/null
/usr/lib/libicuuc.so.66
/usr/lib/libicuuc.so.66.1

**Comment by fiaxh** [comment]
@LinuxCuba We don't have an OBS repository for kaOS, thus I assume you're using the one for ArchLinux. ArchLinux currently has version 67 of libicuuc, while kaOS only has version 66 so far. Since we built the package on the latest ArchLinux, it is linked against version 67.

Until kaOS updates its libicuuc version, you could [compile Dino yourself](https://github.com/dino/dino#build).
