### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by Sylvhem** [dino/dino#548]
Dino currently doesn't support the WebP image format. As such, if someone is using a WebP picture as their avatar or sends one in a conversation, Dino won't be able to display it.
I suggest to add WebP support to Dino in order to make it able to at least display those images. It would solve #227.

Related specifications:
* [XEP-0054: vcard-temp](https://xmpp.org/extensions/xep-0054.html)
* [XEP-0084: User Avatar](https://xmpp.org/extensions/xep-0084.html)
* [XEP-0292: vCard4 Over XMPP](https://xmpp.org/extensions/xep-0292.html)
* [WebP Container Specification](https://developers.google.com/speed/webp/docs/riff_container)

**Comment by fiaxh** [comment]
- [XEP-0084: User Avatar](https://xmpp.org/extensions/xep-0084.html) specifies that the "one of the formats MUST be "image/png" **to ensure interoperability**".
- [XEP-0153: vCard-Based Avatars](https://xmpp.org/extensions/xep-0153.html) specifies that images "SHOULD be image/gif, image/jpeg, or image/png".
- Conversations uploaded WebP images at some point, but switched to JPG a while ago.

Supporting WebP would require an additional (not much installed) dependency, which I don't think is justifiable given the points above. Also, #227 is mostly caused by another issue.

**Comment by Sylvhem** [comment]
My mistake, I didn't read XEP-0084 before opening this, only XEP-0153.
However, I didn't open this issue only for avatars. Since WebP is becoming a more common format, I thought it may be a good idea to implement it in order to open images sent in conversations.

**Comment by qoheniac** [comment]
Maybe a hint to [webp-pixbuf-loader](https://github.com/aruiz/webp-pixbuf-loader) could be added to the wiki as an optional dependency under [Build](https://github.com/dino/dino/wiki/Build) or in the [FAQ](https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)) so that it's easier to find?
