### ISSUE TITLE
Open large image preview when clicking the image instead of a small button

### ISSUE THREAD

**Issue by roobre** [dino/dino#555]
Currently, to open a large view of an image received from http, you have to first hover the image, wait for a small button to appear, and then click that button. The button disappears if you move the mouse too much and you have to repeat the process again. This makes opening images uncomfortable, in my opinion, and I cannot think about any reason to not just doing the same action when clicking anywhere in the image.

Maybe I'm missing something with this proposal so feedback is appreciated. If you agree, I can probably work on a PR for this.

**Comment by fiaxh** [comment]
One reason for showing a button on hover is discoverability. A user will discover and learn that the option to enlarge the image exists by hovering the image and seeing the button appear. However, clicking onto everything to see what it does is not a typical behavior.

One could also make your suggestion discoverable by e.g. putting an transparent white layer over the whole image on hover and displaying an enlarge icon in the middle of it. I'd vote against doing this because of other plans we have for the future of the UI:

- There might be more then one option for an image e.g. there might additionally be an option to forward the image to someone else. This isn't really compatible with clicking on the whole image.
- We plan to display options (e.g. reply, correct) for a message on hover. This could be done with buttons similar to the one currently appearing on image hover. A consistent hovering experience between messages and images would be nice.

**Comment by roobre** [comment]
Hi,

Sorry for the late response, I've been quite busy this days. I'd like to have a bit more discussion on this, if you are ok with that.
I see you are not considering right clicking (or, for what it matters, long-pressing) actions in your message. Why is this? Because we could do something similar to what the telegram desktop app does: Click (or tap) the image to enlarge, right click (or long press) to show a menu with less common options. I think the frequency of use is important here: Most of the time, the user will want to see the image. Then, they might want to forward, store, or do anything else, but those are (in my opinion) edge cases. Why should be the primary action hidden in a show-on-hover button? Most users will assume they *can* enlarge the image, so clicking it seems intuitive.

About your proposal of the big, on hover button, I kind of like it too. Nothing would prevent us from adding more options to that layer you talk about, does it? Like, a big expand button, and a row in the botton with other options (icons for save and forward, for example)

![shittymockup](https://user-images.githubusercontent.com/969721/56892148-02178f00-6a7f-11e9-9272-0157a0966da1.png)

(Shitty mockup, but you get the idea, I hope)
