### ISSUE TITLE
TLS verification does not function

### ISSUE THREAD

**Issue by IamPARANOID** [dino/dino#606]
Upon connecting to a LAN-only server, this error is received:

```
Could not establish a secure connection

The server could not prove that it is [numerical LAN IP].
Its security certificate is not trusted by your computer's operating system.
```

So, I retrieve the key from the XMPP server:
```openssl s_client -connect host:5222 </dev/null -starttls xmpp```
Paste it into a .crt file, and do:
```sudo trust anchor host.crt```
Trying again it then delivers this error:
```
Could not establish a secure connection

The server could not prove that it is [numerical LAN IP].
Its security certificate is issued to another domain.
```

What gives?

**Comment by fiaxh** [comment]
It seems you entered `localpart@LAN_IP` as a JID, however the domain name which the SSL certificate is issued for, is not `LAN_IP`.
The domainpart of the JID and the domain name the SSL certificate is issued for need to be the same address for the certificate to be valid.

**Comment by IamPARANOID** [comment]
I don't think so?
The certificate given by ``openssl s_client -connect host:5222 </dev/null -starttls xmpp`` is the same as the certificate for the same host on the host machine, which is the same as the one trusted by ``anchor``.

**Comment by mar-v-in** [comment]
@IamPARANOID trusting a certificate means to accept it as a certificate for the namen provided in the common name (CN) and/or subject alternative name (SAN) parts of the certificate. It is not generally trusted for everything. If the certificate's CN/SAN do not include the JIDs domainpart (the part after the @ symbol) it's not a valid certificate for connecting to that server and the issue is not about trust.

You mentioned your error message says "The server could not prove that it is [numerical LAN IP]." While it is technically possible to include ip addresses as a SAN in certificates, this is basically unsupported in most applications. Dino does whatever your local GnuTLS library supports, we don't have any special handling for ip address SANs.
