### ISSUE TITLE
Make avatars darker in dark mode

### ISSUE THREAD

**Issue by Zash** [dino/dino#612]
Avatars of offline users are shown in grayscale and with increased brightness.
This looks a bit off in dark mode, they should probably be made darker instead.

**Comment by roobre** [comment]
I've been trying to give this a shot, but this seems more complicated than what it may sound. The main concern is that GTK is style-based so I think there is no easy way to check "am I on a dark theme?". 

Given this, I thought that overalying the current background color on top of the grayscale image might be an option, but it turns out that since GTK has gone full css, there is no reliable way of getting the current background color programatically. Previously there was [get_background_color](https://valadoc.org/gtk+-3.0/Gtk.StyleContext.get_background_color.html), but it is deprecated now because:

> The only reason why you would call get_background_color is to use the returned value to draw the background with it.

On top of that, the result is not very eye-pleasant either, at least with arc-dark.

Maybe I can give it another shot if someone finds out how to proceed on this.

**Comment by Zash** [comment]
Maybe it's possible to make it transparent via CSS instead of applying the transform manually?

**Comment by roobre** [comment]
Judging by [this comment](https://github.com/dino/dino/blob/master/main/src/ui/avatar_image.vala#L177), I'd say the original intention was to make the image more visible (no idea why, though). Making it transparent would either break this original intention, or require branching on whether the current theme is dark or light (which cannot be easily done)

**Comment by fiaxh** [comment]
Offline contacts are no longer shown in greyscale.
