### ISSUE TITLE
Detect links even without http:// or https://

### ISSUE THREAD

**Issue by Perflyst** [dino/dino#622]
Dino does not detect links without http:// or https://

**Comment by fiaxh** [comment]
I don't think we want to use heuristics to detect links:
- Especially with the large number of new TLDs, we'd have a significant false-positive rate
- We don't know whether to assume http:// or https://, mind that there are still websites that don't support https://
- Just because someone sends a domain name, doesn't mean it's accessible via HTTP(S)
