### ISSUE TITLE
No indication of delivery error

### ISSUE THREAD

**Issue by Zash** [dino/dino#672]
Eg if there's a problem establishing a server-to-server connection or other problem when trying to deliver a message, an error reply is returned, simliar to this:

```xml
<message id="123" type="error" to="me@chat.example/Dino" from="jdoe@example.com">
  <error type="wait" by="chat.example">
    <remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
    <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Server-to-server connection failed: Remote server's certificate has expired</text>
  </error>
</message>
```

The only indication that there's something wrong is the lack a receipt checkmark. I think an error reply deserves a bit more noise. Red scary :x: or something? Also useful to have the error condition and (optional) text message available to show the service admin.

**Comment by Echolon** [comment]
Rel: **Warn user on first insecure chat message** #76 
Rel. **Provide some way to tell whether the message was sent** #225

**Comment by bowlofeggs** [comment]
+1 to the proposal. Another thing that might be nice would be if Dino automatically retried to deliver a few times (and then give up with a red scary X if it still can't deliver the message…)

**Comment by phryk** [comment]
I stumbled onto this issue because I'm currently in the process of extending [mod_e2e_policy] to build a usable but secure XMPP service.

I'm probably going to remove proper error indication for now and fall back on sending warnings about lack of E2EE in a different convo because I apparently can't depend on core functionality being honored by clients, which is a shame because error message stanzas seem to be the only thing that'd enable me to show what's wrong within the affected convo, meaning a net downgrade to UX. :<

[mod_e2e_policy]: https://modules.prosody.im/mod_e2e_policy
