### ISSUE TITLE
Dino treats last ` as a valid URL character if URL is encloded by back-tiks

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#695]
If a URL is put into back-tiks like  \`https://dino.im`, Dino counts the back-tik on the right to the URL.

However, afaik a ` is not directly allowed after the TLD, but is valid as a query argument:

`https://www.startpage.com/do/dsearch?query=%60+url&cat=web&pl=opensearch&language=english`,

where it becomes encoded to `%60`.

**Comment by ericschdt** [comment]
Just another example:

~https://dino.im~ should be crossed out, but actually takes the last tilde into the url \~[https://dino.im~](https://dino.im~)

**Comment by ericschdt** [comment]
Since https://github.com/dino/dino/commit/81bde9197bd83ce37baac13924c782c02353a172 `*https://dino.im*` becomes \*[https://dino.im*](https://dino.im*)

**Comment by fiaxh** [comment]
Both were addressed in 5e1f646cbcc0cc4ac08faf76afe5becba4dfd4c6.

**Comment by ericschdt** [comment]
> Both were addressed in [5e1f646](https://github.com/dino/dino/commit/5e1f646cbcc0cc4ac08faf76afe5becba4dfd4c6).

But now `_https://dino.im_` is italic but no longer recognized as an URL. Is that on purpose?

**Comment by mar-v-in** [comment]
_https://dino.im_ is also not supported by some other clients.

In our case this is because _ is not considered a word boundary in regex, and I guess that's also the reason for many others. While technically we should probably support that (_ is invalid in a uri scheme so indeed this would be possible to handle correctly), for now it's not an issue if we don't handle it.

Does GitHub handle _http://example.com/_ ?
