### ISSUE TITLE
Add send Message button

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#71]
As an alternative to pressing enter.

**Comment by fiaxh** [comment]
Are there actually people who _use_ those buttons on desktop chat applications? If you use a (tablet/notebook) touch display the display keyboard still has an enter key which does the job. An early pre-github version contained a send message button, but I removed it due to the cleaner look. Some programs like telegram and desktop-whatsapp replace a microphone-button with a send-button after text was entered, which is fine because you couldn't use the other button anymore and it would be weird to just remove the button altogether. However for Dino I don't really see a reason to have a send button.

**Comment by NicoHood** [comment]
I generally agree with this. But I had some usecases where I needed this. I dont remember all use cases but imagine something like this:

You write a text and wait for it to send. Maybe your partner is still writing stuff (I am mostly faster in writing and dont want to interrupt). Thatswhy I wait. Then I go outside the window. He/She answers and you just want to send the message with the mouse and then move back to the browser. This safes you hitting enter instead of clicking + enter.

I know this is minor, and I generally agree. But a send button is something that should not be missing in a good chat program. It can be small though, similar to the current height. Lets say ~0,5 by 0,5 cm. Just as option :)

**Comment by NicoHood** [comment]
Another issue:
The num block enter button gives a linefeed and does not send the message. This is not expected. shift + enter normally gives a line feed (which works) and both enter buttons work the same.

**Comment by NicoHood** [comment]
On my laptop, depending on the numlock state, the enter button has different functions. And if its in the numblock enter mode, I have no chance to send a message. And since a normal button is missing, I just cannot submit my message. Now in my case I found that I can switch this behaviour. But there could be situations where this is impossible.

As you can see, there are always usecases for an old style send button. Also I recommend to change the enter behavior.

**Comment by fiaxh** [comment]
b09a056 fixes the behavior of the numpad enter key, so no need for a send button anymore ;)

**Comment by NicoHood** [comment]
@fiaxh as described before there are still use cases. And I exactly had this yesterday. Wrote text, switched windows and wanted to click on send. Still thinking this is necessary.

**Comment by d9h02f** [comment]
I think when Dino gets support for sending images, it would make sense to do it Conversations-style: if there is no text entered, you get a button which allows you to select an image, if there is text entered, that button turns into a send button.

**Comment by fiaxh** [comment]
@NicoHood The video which you've linked even mentions a chat without a send button as a positive example :) https://youtu.be/r2CbbBLVaPk?t=85 

@d9h02f A button for sending files should probably go into the header bar. Actually that's also how it is in Conversations. Having it instead of the send button is just a second option offered in some cases.

**Comment by d9h02f** [comment]
Huh, only now did I get a notification for your comment. You're right, I was thinking of Signal. A button in the header bar makes sense.
