### ISSUE TITLE
Received emojis from Conversations appear bigger than sent ones from Dino

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#741]
Dino 0.1.0
Conversations 2.6.x

![dino_smileys](https://user-images.githubusercontent.com/43318127/73981780-e94fda00-492a-11ea-9aa6-3405a4d6e6c2.png)

Personally I would go with the bigger variant!

**Comment by mar-v-in** [comment]
The GNOME emoji picker adds unnecessary emoji qualifiers that are not correctly understood as an emoji anymore. The behavior with bigger emojis is the intended one. When you copy and paste emojis from Conversations or some websites instead of using the GNOME emoji picker it should work correctly.

We can probably change the behavior of the GNOME emoji picker though.

**Comment by PilzAdam** [comment]
This seems fixed in current master (25751c88ced9d312aef22135ee2f68c2edb71b7e fixed it probably).

**Comment by mar-v-in** [comment]
Indeed. Thanks for keeping track.
