### ISSUE TITLE
MUCs & user avatar lost, after server failure

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#753]
Hei,
there is some problem with my xmpp provider. So all the MUCs were lost, also my avatar is gone in dino.

## Faulty Behavior
When I go to "burger menu" -> "join channel"
my MUCs list is gone.. and also on my room list all the MUCs are gone

## Expected Behavior
I expect that dino has a behavior more like conversations, where the user is more in control.. which means all bookmarks are gone in conversations, but the MUCs are still open, and the avatar is still there

**Comment by licaon-kter** [comment]
So you were connected when this happened?

**Comment by albjeremias** [comment]
> So you were connected when this happened?
I don't think so.. but im not sure

> /LE:
> The reversed problem is that I deliberately remove a bookmark in another client and Dino refuses me my control and still keeps it open.

interesting...

**Comment by fiaxh** [comment]
Dino uses the bookmarks list (and the autojoin flag) as a means of syncing joined MUCs between clients. If you remove a bookmark on another client (or set autojoin=false), it is expectable that you do it because you don't want to join the MUC anymore. Thus, in the normal case, this behavior should benefit the user.

In your case it confused you more than Conversations' behavior, but the underlying problem was a server issue and it should be fixed on the server side. We shouldn't compromise the "normal case" behavior because some server showed a rare bug.

In the future, Dino might remember previously joined MUCs (independently of bookmarks) to help with auto-completion results, though.

**Comment by albjeremias** [comment]
ok, i changed the title.. if u want u can open :P i actually meant to create a feature request after i realized that it was on server side! anyway.. thank u a lot for dino! \o/

**Comment by albjeremias** [comment]
@fiaxh please..  can we reopen this?
 this is a very bad user experience... i lost all my bookmarks in dino, and they are all kept in conversations.. im not the first person this happens.. 

> i wouldnt say it was upgrade that deleted it but probably bug somewhere in between, where perhaps client was trying to access stuff from server and if it didnt get it it assumned its deleted and send deletion to the server or something
