### ISSUE TITLE
[feature/handy] window controls don't move between headerbar sections on leaflet fold or view change

### ISSUE THREAD

**Issue by GabMus** [dino/dino#786]
Short video showing the problem

https://i.imgur.com/UPvY9n5.mp4

**Comment by mar-v-in** [comment]
This is intended. There is not enough room to display window control buttons in conversation view, so they are only shown in list view. You can still reach them by pressing the back button first or by using right click.

**Comment by GabMus** [comment]
I don't know if this is a good reason tbh, I think there's plenty of room for them to fit. Plus on phone form factors they should be hidden anyway, this only reduces usability

**Comment by bertob** [comment]
As one of the people who came up with this design pattern I can confirm that the idea is to show window controls on every panel, and every other app using the leaflet does it that way. It doesn't make sense to be able to close the window depending on where you are in the hierarchy.

Also, by default there's only one close button, so this is much less of an issue than it looks like from that video.

**Comment by mar-v-in** [comment]
How it is today, there is definitely not enough room to have window controls *and* the 3 buttons we already have in the headerbar *and* the room title and subtitle *and* the back button when the window width is such small that it is in folded view. In you example video, the room doesn't have a topic, so the subtitle is not displayed and even in your cast if you imagine there to be 3 additional window control buttons, the title would barely fit in the title bar.

We planned to merge our three buttons into a menu in folded view (or always) anyway and then a close button might fit. We also have to do other adjustments for mobile design / small windows.

The libhandy support is very much early state and experimental and is only there so that people using it in experimental setups on *phones* can actually use Dino in handheld mode (before it was only usable in landscape mode). Many dialogs still require going to landscape mode though, just the normal chat is somewhat usable now.

**Comment by Echolon** [comment]
rel. #178

**Comment by mimi89999** [comment]
Hello,
This was changed in https://github.com/dino/dino/pull/961.
