### ISSUE TITLE
Dino can't show inline images by default

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#813]
I think I recall that Dino needs some other package to show images inline is that correct?

I think it should be considered to make packaged Dino (in the case I noticed it, it was Debian) dependent on the package that is needed to show the images inline. I think it's a core enough feature to require users to have the dependency.

The main argumentation for this is that it's entirely impossible for a user to know how to get the images to work except for asking in the Dino chat or the GitHub.

**Comment by fiaxh** [comment]
> I think I recall that Dino needs some other package to show images inline is that correct?
No, that's not true. Dino doesn't need additional optional packages to show images.

What version of Dino are you experiencing problems with?

**Comment by stevenroose** [comment]
Good question. He's using `dino-im` on Ubuntu IIRC. Not sure which Ubuntu and which version. I asked him will try remember to report back.

**Comment by fiaxh** [comment]
Ubuntu unfortunately has some terribly old Dino versions in it's repositories. The 18.04 LTS version has a Dino development version from early 2018, and (encrypted) image preview likely didn't work properly back then.
I'm closing this since I assume that this is an issue with an outdated package, not with Dino. If you have indications to the contrary, drop a message and I'll reopen it.
