### ISSUE TITLE
OMEMO: Long Message with invalid tag

### ISSUE THREAD

**Issue by genofire** [dino/dino#829]
Somebody other send a long OMEMO message from a `dino-0.1.0-3`
  -  not working
      -  `100AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
  - working
      - `95AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

Test it with recipient client:
- Conversations / Pix-Art messenger : Does not appear
- other Dino: `[This message is OMEMO encrypted]`
- gajim: Does not appear either ([Issue](https://dev.gajim.org/gajim/gajim-plugins/-/issues/496) for this)

---

Is it maybe related / fixed in #781 already?
Or related to #777 ?

**Comment by mar-v-in** [comment]
Is the sending device using a aarch64/armv8 cpu?

**Comment by genofire** [comment]
I am asking for this information - but i believe it is a pinebook with arm, yes.

**Comment by mar-v-in** [comment]
There is a bug in libgcrypt on aarch64/armv8 architecture causing this issue. This has been [reported and fixed upstream](https://dev.gnupg.org/D497). The issue is fixed in Debian bullseye and Ubuntu 20.04 (since `libgcrypt20-1.8.5-4`) but not anywhere else afaik. Only possible workaround on other systems is to build a patched libgcrypt.

**Comment by genofire** [comment]
hmm okay, there was no official release of libgcrypt since 1.8.5 ... in manjaro and archlinux they are on 1.8.5-2

**Comment by mar-v-in** [comment]
This is a bug on the sending side, you can't fix it on the receiving end, so what matters is only what is running on the Pinebook.

**Comment by genofire** [comment]
I got it already, i believe it is a manjaro - thats why i make this research ;) - https://discover.manjaro.org/packages/libgcrypt and https://www.archlinux.org/packages/?q=libgcrypt

**Comment by mar-v-in** [comment]
Yes, ArchLinux and Manjaro don't have the patch included. Maybe open an issue with them and ask if they are willing to include the [patch](https://dev.gnupg.org/D497) before `1.8.6` is officially released - just as Debian/Ubuntu did?

**Comment by selurvedu** [comment]
I believe this ticket can be closed now as Libgcrypt 1.8.6 was released on 2020-07-06: https://dev.gnupg.org/T4985

It's already in Fedora 33, Debian Testing, openSUSE Tumbleweed, Arch, Manjaro, Gentoo and other distros. Ubuntu 20.10 still has libgcrypt 1.8.5 but that's okay since they grabbed the patch from Debian.

> This has been [reported and fixed upstream](https://dev.gnupg.org/D497).

@mar-v-in whoa, you showed us some impressive top tier debugging skills! It must've taken a ton of time to troubleshoot this.

**Comment by genofire** [comment]
Testit and it works -> thanks
