### ISSUE TITLE
Group chat room names are not correct, cannot join more than 4 randomly selected rooms

### ISSUE THREAD

**Issue by Riifta** [dino/dino#910]
After signing in to my XMPP server I am presented with the below. Unlike the screenshots on the website, the group chat room names don't appear correctly and I'm not able to join any other rooms other than these 4 that seem to have been randomly chosen.

![image](https://user-images.githubusercontent.com/9170186/93410884-3cd0d000-f8dd-11ea-83fd-e53944bc5e4b.png)

Trying to join more than these 4 rooms (via Join Channel) only gives me the 4 options as well. It doesn't appear to have anyway to pull the room list. Note that the room names are at least correct for these 4 rooms on the Join Channel dialog.

Is there a way I can **a.** have the correct room names appear and **b.** tell Dino what rooms I want to join/get a list of rooms/join more than just these 4?

**Comment by licaon-kter** [comment]
The room list is the one in your bookmarks....add more with + 


If you want to list more (public) rooms from your server or from the ecosystem (https://search.jabber.network)... Dino does not have this feature (yet)...eg. Use Conversations to list them

**Comment by Riifta** [comment]
The + doesn't actually let me join more rooms (it simply keeps Join blanked out even if I manually type it). I also cannot find the "Conversions" to list them.

Addtionally, as I mentioned, the names for the 4 that do come up aren't correct.

**Comment by licaon-kter** [comment]
You need to type more: roomname@conference.domain.tld and set a nick...

Why does Conversations say exactly?

What version of Dino?

**Comment by Riifta** [comment]
That worked (yay) but the UI is pretty unintuitive. Conversations doesn't list them either, it only lists the individual users on the server itself. The four original channels are also still not named properly as well.

Dino version is 0.1.0, that comes with Fedora 32.

**Comment by fiaxh** [comment]
As far as I see, Pidgin does not store information about your joined channels on the server. It might "work" in Pidgin, but that is only local state and has nothing to do with XMPP bookmarks. See this [open Pidgin issue](https://developer.pidgin.im/ticket/6353) about adding bookmark support.

The same goes for the names. Dino and Conversation can't know the room names you set in Pidgin, because Pidgin doesn't seem to share them.

You can set the bookmark name in Dino by filling in the "Alias" field when adding a bookmark (given the bookmark does not yet exist).
