### ISSUE TITLE
Failed to upgrade to database version 18

### ISSUE THREAD

**Issue by gllmhyt** [dino/dino#970]
As I was testing between 0.2.0 release tag and latest git tag back and forth, I stumbled accross this error:

```
(dino:27836): libdino-ERROR **: 16:06:44.409: database.vala:410: Failed to upgrade to database version 18: SQLite error: 1 - index contentitem_conversation_hide_time_idx already exists
```

**Comment by fiaxh** [comment]
This error happened because you switched back and forth between versions. We don't implement methods for downgrading the database, thus downgrading the Dino version while using the same database won't work. I made it work for this database upgrade specifically, but generally switching back and forth is unsupported.
