### ISSUE TITLE
Password account in cleartext

### ISSUE THREAD

**Issue by FrancescoDiSalesGithub** [dino/dino#981]
Good evening as I was testing DINO, I've found in the home folder and specifically in the directory .local/share/dino a file:
dino.db

As I tried to open it with sqlite i've seen some tables, but in this issue I'm going to focus on the account table.
Doing a simple SQL query:

Select* from account

I've found the password of my account in cleartext
Now should it be atleast crypted with a hash function?

Thank you for your attention

**Comment by mimi89999** [comment]
> Now should it be atleast crypted with a hash function?

That's not quite how things work.

**Comment by FrancescoDiSalesGithub** [comment]
> > Now should it be atleast crypted with a hash function?
> 
> That's not quite how things work.

yes I know I don't know the right word.

**Comment by fiaxh** [comment]
In general, you need a password in order to login to your account. If we were to encrypt the password in the database, we have to decrypt it somehow before connecting. That would mean the user has to enter the password-encryption-password on every startup.

You could encrypt the whole database and enter a password on each start of Dino. Here's how to achieve that: https://github.com/dino/dino/issues/745#issuecomment-588436869.

As has been mentioned, the password can be stored in a keyring instead (#102).
With many servers it's also possible to not store a password but a SCRAM key in the database, the path to that is outlined here https://github.com/dino/dino/pull/254#issuecomment-439067200.
