### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by omexlu** [dino/dino#999]
Hello,

Does Dino also have the ability to set a channel like Gajim can?

Thanks in advance.

**Comment by licaon-kter** [comment]
Set? You mean create? Yes, upper left plus, join, lower left plus, channelname@conference.domain.tld (note that conference might be named differently)

**Comment by omexlu** [comment]
Yes, but I mean can i also make various settings in your own channel as is possible with Gajim?

**Comment by licaon-kter** [comment]
Yes, after creation, upper righn menu

**Comment by omexlu** [comment]
I i will try, do you know a site where i can create a channel for free?

**Comment by licaon-kter** [comment]
I'd guess that most servers you have an account on allow this.

**Comment by omexlu** [comment]
Works very well, is it possible that dino can not receive/send message if the other person is not on the contact list?
I don't find any settings about this?

**Comment by licaon-kter** [comment]
There's no such limitation in Dino, you'd need to explain, unencrypted? OMEMO? Maybe the other sever blocks non contacts by default...etc

**Comment by omexlu** [comment]
i tested unencrypted with OMEMO, until i don't add the other part in contact list i can't reach them.

**Comment by fiaxh** [comment]
Dino should be able to send and receive unencrypted messages regardless of whether a person is in your contact list or not. Sending OMEMO encrypted messages can be a problem without mutual subscription, though. That's because the key (or the list of keys) of your contact might only be visible to contacts. If you have more questions about how to use Dino you can also join our channel at `chat@dino.im`.
